services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www/html:ro
    ports:
      - '3380:80'

  mariadb:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_DATABASE=ipdb
      - MARIADB_USER=ipdb
      - MARIADB_PASSWORD=ipdb
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d:ro