ALTER TABLE atkIps
    MODIFY COLUMN addedat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN lastseen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE db_schema_version SET version = 202605200002 WHERE id = 1;
