name: Pest

on:
  push: {}
  pull_request: {}
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare config
        run: cp _config.dist.php _config.php

      - name: Install composer dependencies
        run: sudo docker compose -f .devcontainer/docker-compose.yml -f docker-compose.ci.yaml run app composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install node dependencies
        run: sudo docker compose -f .devcontainer/docker-compose.yml -f docker-compose.ci.yaml run app npm ci

      - name: Install playwright
        run: sudo docker compose -f .devcontainer/docker-compose.yml -f docker-compose.ci.yaml run app npx playwright install --with-deps

      - name: Start server
        run: sudo docker compose -f .devcontainer/docker-compose.yml -f docker-compose.ci.yaml run -d -p 8080:8080 app

      - name: Run tests
        run: sudo docker compose -f .devcontainer/docker-compose.yml -f docker-compose.ci.yaml run app ./vendor/bin/pest --ci

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            tests/Browser/Screenshots
          if-no-files-found: ignore
          retention-days: 7

      - name: Tear down
        if: always()
        run: sudo docker compose -f .devcontainer/docker-compose.yml down --volumes --remove-orphans --rmi all
